import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";
import { BiSolidSchool } from "react-icons/bi";
import linksaverssImg from "@/public/linksaverss.png";
import rentacarssImg from "@/public/rentacarss.png";
import promptaissImg from "@/public/promptaiss.png";
import menuadvisorssImg from "@/public/menuadvisorss.png";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "SAP ABAP DEVELOPER INTERNSHIP ",
    location: "Finpro Consulting",
    description:
      " I created programs involving ALV grids, dynamic screen updates, and interactive reports. I gained skills such as sending emails, calendar integrations, generating HTML outputs for web-based applications. integrating Smartforms for PDF, Excel generation and managing data in maintenance tables. Throughout projects, I gained experience with S/4HANA and applied Object-Oriented Programming (OOP) principles to build robust and efficient solutions. ",
    icon: React.createElement(BiSolidSchool),
    date: "2024 July - September ",
  },
] as const;

export const projectsData = [
  {
    title: "Menu Advisor",
    description:
      "A platform users can navigate between nearby food and beverage establishments, rate them, comment them and see the menu. Store owners can add product on the menu and make changes in their store page.",
    tags: ["React", "Next.js", "Middleware", "Tailwind"],
    imageUrl: menuadvisorssImg,
  },
  {
    title: "PromptAI",
    description:
      "The website serves as a platform where users can discover helpful AI prompts generated by others. Additionally, users can share their own favorite AI prompts Access to the app is handled through Google Authenticator",
    tags: ["React", "Next.js", "MongoDB", "Tailwind"],
    imageUrl: promptaissImg,
  },
  {
    title: "Rent a Car App",
    description:
      "Developed with React. This project using firebase as a backend. User can sign in to system and rent a car, and host can see the income and reviews on dashboard",
    tags: ["React", "Firebase"],
    imageUrl: rentacarssImg,
  },
  {
    title: "Link Saver Chrome Extension",
    description:
      "An extension helps you keep tracking your links. It was developed in HTML , CSS and Javascript Dom.",
    tags: ["JavaScript", "HTML", "CSS"],
    imageUrl: linksaverssImg,
  },
] as const;

export const skillsData = [
  "JAVA",
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Next.js",
  "Git",
  "Tailwind",
  "Firebase",
  "MongoDB",
  "TypeScript",
  "SAP ABAP",
] as const;
