import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { FaReact } from "react-icons/fa";
import { LuGraduationCap } from "react-icons/lu";
import linksaverssImg from "@/public/linksaverss.png";
import rentacarssImg from "@/public/rentacarss.png";
import promptaissImg from "@/public/promptaiss.png";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "1st Internship",
    location: "Somewhere",
    description:
      "Internship description goes here.",
    icon: React.createElement(LuGraduationCap),
    date: "2024",
  },
] as const;

export const projectsData = [
  {
    title: "PromptAI",
    description:
      "The website serves as a platform where users can discover helpful AI prompts generated by others. Additionally, users can share their own favorite AI prompts Access to the app is handled through Google Authenticator",
    tags: ["React", "Next.js", "MongoDB", "Tailwind"],
    imageUrl: promptaissImg,
  },
  {
    title: "Rent a Car App",
    description:
      "Developed with React. This project using firebase as a backend. User can sign in to system and rent a car, and host can see the income and reviews on dashboard",
    tags: ["React", "Firebase"],
    imageUrl: rentacarssImg,
  },
  {
    title: "Link Saver Chrome Extension",
    description:
      "An extension helps you keep tracking your links. It was developed in HTML , CSS and Javascript Dom.",
    tags: ["JavaScript", "HTML", "CSS"],
    imageUrl: linksaverssImg,
  },
] as const;

export const skillsData = [
  "JAVA",
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Next.js",
  "Git",
  "Tailwind",
  "Firebase",
  "MongoDB",
  "TypeScript",
] as const;
